# -*- coding: utf-8 -*-
"""Diffusers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhOTu6qgpPymTrrJ1zLMVDHt4-yIUNO6
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qq -U diffusers datasets transformers accelerate ftfy pyarrow

from huggingface_hub import notebook_login

notebook_login()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !sudo apt -qq install git-lfs
# !git config --global credential.helper store

import numpy as np
import torch
import torchvision
import torch.nn.functional as F
from matplotlib import pyplot as plt
from PIL import Image

def show_images(x):
  x = x * 0.5 + 0.5
  grid = torchvision.utils.make_grid(x)
  grid_im = grid.detach().cpu().premute(1,2,0).clip(0,1) * 255
  grid_im = Image.fromarray(np.array(grid_im).astype(np.uint8))
  return grid_im

def make_grid(images, size=64):
  output_im = Image.new("RGB", (size * len(images), size))
  for i,im in enumerate(images):
    output_im.paste(im.resize((size, size)), (i * size, 0))
  return output_im